# Generated by Django 5.2.17 on 2026-09-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hero_id",
                    models.PositiveIntegerField(unique=True, verbose_name="ID героя"),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Имя")),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="Титул"),
                ),
                (
                    "quality",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Редкость"
                    ),
                ),
                (
                    "season",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Сезон"
                    ),
                ),
                ("flying", models.BooleanField(default=False, verbose_name="Летающий")),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Список объектов {id, name, rage_cost, description, upgrade, holistic, skill_enhanced}",
                        verbose_name="Навыки",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Герой",
                "verbose_name_plural": "Герои",
                "ordering": ["hero_id"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Имя"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Тип урона"
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Класс войск"
                    ),
                ),
                (
                    "max_strength",
                    models.PositiveIntegerField(default=0, verbose_name="Сила (макс.)"),
                ),
                (
                    "max_agility",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ловкость (макс.)"
                    ),
                ),
                (
                    "max_intelligence",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Интеллект (макс.)"
                    ),
                ),
                (
                    "max_endurance",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Выносливость (макс.)"
                    ),
                ),
                (
                    "max_spirit",
                    models.PositiveIntegerField(default=0, verbose_name="Дух (макс.)"),
                ),
                (
                    "max_luck",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Удача (макс.)"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Сумма характеристик"
                    ),
                ),
                (
                    "portrait",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Портрет (путь)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Питомец",
                "verbose_name_plural": "Питомцы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PetSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "attribute",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Характеристика"
                    ),
                ),
                (
                    "talent",
                    models.BooleanField(
                        default=False, verbose_name="Врождённый талант"
                    ),
                ),
                (
                    "pet_exclusive",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Эксклюзив питомца"
                    ),
                ),
                (
                    "dependency",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Зависимость (требуемый навык)",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Тип урона"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Категория"
                    ),
                ),
                (
                    "costs",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Стоимость по уровням"
                    ),
                ),
                (
                    "values",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Значения по уровням"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Иконка (путь)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Навык питомца",
                "verbose_name_plural": "Навыки питомцев",
                "ordering": ["name"],
            },
        ),
    ]
