# Generated by Django 5.2.17 on 2026-09-11 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alliance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alliance_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="ID альянса"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название"
                    ),
                ),
                (
                    "abbr",
                    models.CharField(blank=True, max_length=20, verbose_name="Тег"),
                ),
                (
                    "logo",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Герб (код)"
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(blank=True, max_length=120, verbose_name="Лидер"),
                ),
                (
                    "owner_id",
                    models.PositiveBigIntegerField(
                        blank=True, null=True, verbose_name="ID лидера"
                    ),
                ),
                (
                    "ori_server_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Исходный сервер"
                    ),
                ),
                (
                    "born_area_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Стартовая зона"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Альянс",
                "verbose_name_plural": "Альянсы",
                "ordering": ["server_id", "name"],
            },
        ),
        migrations.CreateModel(
            name="RankSendStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Тип рейтинга"
                    ),
                ),
                (
                    "template_name",
                    models.CharField(blank=True, max_length=150, verbose_name="Шаблон"),
                ),
                (
                    "send_count",
                    models.PositiveIntegerField(default=0, verbose_name="Отправок"),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последняя отправка"
                    ),
                ),
                (
                    "last_ack_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последнее подтверждение"
                    ),
                ),
                (
                    "last_rows_updated",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Обновлено строк"
                    ),
                ),
                (
                    "last_changed_rows",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Изменено строк"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика рассылки рейтинга",
                "verbose_name_plural": "Статистика рассылки рейтингов",
                "ordering": ["rank_name"],
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "server_id",
                    models.PositiveIntegerField(unique=True, verbose_name="ID сервера"),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Название"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Заметки")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Сервер",
                "verbose_name_plural": "Серверы",
                "ordering": ["server_id"],
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_id",
                    models.PositiveBigIntegerField(
                        unique=True, verbose_name="ID игрока"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=120, verbose_name="Ник"),
                ),
                (
                    "alliance_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Альянс (название)"
                    ),
                ),
                (
                    "alliance_abbr",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Альянс (тег)"
                    ),
                ),
                (
                    "town_center_lvl",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ратуша, уровень"
                    ),
                ),
                (
                    "ori_server_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Исходный сервер"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alliance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="members",
                        to="ranking.alliance",
                        to_field="alliance_id",
                        verbose_name="Альянс",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="ranking.server",
                        to_field="server_id",
                        verbose_name="Сервер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "ordering": ["server_id", "name"],
            },
        ),
        migrations.AddField(
            model_name="alliance",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alliances",
                to="ranking.server",
                to_field="server_id",
                verbose_name="Сервер",
            ),
        ),
        migrations.CreateModel(
            name="AllianceRankEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_name",
                    models.CharField(max_length=150, verbose_name="Тип рейтинга"),
                ),
                (
                    "kind",
                    models.CharField(blank=True, max_length=40, verbose_name="kind"),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "pre_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Прошлое место"
                    ),
                ),
                ("score", models.BigIntegerField(default=0, verbose_name="Очки")),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Снято"),
                ),
                (
                    "alliance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_entries",
                        to="ranking.alliance",
                        to_field="alliance_id",
                        verbose_name="Альянс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг альянса",
                "verbose_name_plural": "Рейтинги альянсов",
                "indexes": [
                    models.Index(
                        fields=["rank_name", "rank"],
                        name="ranking_all_rank_na_0edc67_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alliance", "rank_name"), name="uniq_alliance_rankname"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerImmigrateEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_name",
                    models.CharField(max_length=150, verbose_name="Тип рейтинга"),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "pre_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Прошлое место"
                    ),
                ),
                ("score", models.BigIntegerField(default=0, verbose_name="Очки")),
                (
                    "castle_hide_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Замок скрыт до"
                    ),
                ),
                (
                    "player_logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний выход"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Снято"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="immigrate_entries",
                        to="ranking.player",
                        to_field="player_id",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг иммиграции",
                "verbose_name_plural": "Рейтинги иммиграции",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "rank_name"),
                        name="uniq_player_immigrate_rankname",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerRankEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rank_name",
                    models.CharField(max_length=150, verbose_name="Тип рейтинга"),
                ),
                (
                    "kind",
                    models.CharField(blank=True, max_length=40, verbose_name="kind"),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                (
                    "pre_rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Прошлое место"
                    ),
                ),
                ("score", models.BigIntegerField(default=0, verbose_name="Очки")),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Снято"),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rank_entries",
                        to="ranking.player",
                        to_field="player_id",
                        verbose_name="Игрок",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рейтинг игрока",
                "verbose_name_plural": "Рейтинги игроков",
                "indexes": [
                    models.Index(
                        fields=["rank_name", "rank"],
                        name="ranking_pla_rank_na_d5be4c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("player", "rank_name"), name="uniq_player_rankname"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entity_id",
                    models.PositiveBigIntegerField(verbose_name="ID сущности"),
                ),
                (
                    "rank_name",
                    models.CharField(max_length=150, verbose_name="Тип рейтинга"),
                ),
                (
                    "kind",
                    models.CharField(blank=True, max_length=40, verbose_name="kind"),
                ),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Место"
                    ),
                ),
                ("score", models.BigIntegerField(default=0, verbose_name="Очки")),
                (
                    "castle_hide_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Замок скрыт до"
                    ),
                ),
                (
                    "player_logout_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Последний выход"
                    ),
                ),
                (
                    "detail_raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Детали (raw JSON)"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Снято"),
                ),
                (
                    "server",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_details",
                        to="ranking.server",
                        to_field="server_id",
                        verbose_name="Сервер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Детализация очков",
                "verbose_name_plural": "Детализации очков",
                "indexes": [
                    models.Index(
                        fields=["rank_name", "rank"],
                        name="ranking_sco_rank_na_e037b5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity_id", "rank_name"), name="uniq_entity_rankname"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["server", "name"], name="ranking_pla_server__4af553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alliance",
            index=models.Index(
                fields=["server", "name"], name="ranking_all_server__d7c9a7_idx"
            ),
        ),
    ]
